# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ patch-6 ]
  pull_request:
    branches: [ patch-6 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Build for Android ${{matrix.arch}}"
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get ANGLE
        uses: actions/checkout@v2
        with:
          path: 'angle'

      - name: Build ANGLE
        shell: bash
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=`pwd`/depot_tools:$PATH
          echo $PATH
          cd angle
          python3 scripts/bootstrap.py
          gclient sync
          gn gen out/Android
          autoninja -C out/Android

      - name: Upload ANGLE
        uses: actions/upload-artifact@v3
        with:
          name: angle-apk
          path: |
            angle/out/Android/apks
